# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ploodev
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bonzai

provider:
  name: aws
  runtime: nodejs20.x
  deploymentMethod: direct
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            '*'
            # - arn:aws:dynamodb:eu-north-1:571600828520:table/my-todos

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  getRooms:
    handler: functions/getRooms/getRooms.handler
    events:
      - httpApi:
          path: /rooms
          method: GET
  bookRooms:
    handler: functions/bookRooms/bookRooms.handler
    events:
      - httpApi:
          path: /booking
          method: POST

  # UpdateTodo:
  #   handler: functions/UpdateTodo/index.handler
  #   events:
  #     - httpApi:
  #         # path: /todos/{id} om man kan skicka med id
  #         path: /todos/{id}
  #         method: PUT
  # DeleteTodo:
  #   handler: functions/DeleteTodo/index.handler
  #   events:
  #     - httpApi:
  #         # path: /todos/{id} om man kan skicka med id
  #         path: /todos/{id}
  #         method: DELETE

resources:
  Resources:
    RoomTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Rooms
        AttributeDefinitions:
          - AttributeName: 'RoomID'
            AttributeType: 'N'
        KeySchema:
          - AttributeName: 'RoomID'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
